# Generated by Django 3.1.3 on 2021-01-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='slug',
            field=models.SlugField(default='disko', max_length=20),
        ),
    ]
