# Generated by Django 3.1.3 on 2021-01-25 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_ticket_order'),
        ('shares', '0003_auto_20210120_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='share',
            name='city',
            field=models.ManyToManyField(to='movie.City'),
        ),
    ]
