# Generated by Django 3.1.3 on 2021-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0005_pdffiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffiles',
            name='slug',
            field=models.SlugField(default='oleg', max_length=20),
        ),
    ]
