# Generated by Django 3.1.3 on 2021-01-28 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shares', '0006_pdffiles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdffiles',
            name='slug',
            field=models.SlugField(max_length=20),
        ),
    ]
