# Generated by Django 3.1.3 on 2020-12-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='session',
            name='price',
            field=models.IntegerField(default=228),
        ),
    ]
