# Generated by Django 3.1.3 on 2021-01-25 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_ticket_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='carousel',
            field=models.ImageField(blank=True, upload_to='images/movies/carusel/%Y/%M/%D'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_carousel',
            field=models.BooleanField(default=False),
        ),
    ]
