# Generated by Django 3.1.3 on 2021-02-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20210125_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='halls',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cinema',
            name='information',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cinema',
            name='phone',
            field=models.CharField(default='', max_length=11),
        ),
        migrations.AddField(
            model_name='cinema',
            name='places',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('link', models.URLField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.city')),
            ],
        ),
        migrations.CreateModel(
            name='CinemaImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='cinema/None')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.cinema')),
            ],
        ),
    ]
