# Generated by Django 3.1.3 on 2021-02-04 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_sociallinks_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('tq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.titlequestion')),
            ],
        ),
    ]
