# Generated by Django 3.1.3 on 2021-03-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_answer_titlequestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='agelimit',
            name='for_adults',
            field=models.BooleanField(default=False),
        ),
    ]
