# Generated by Django 3.1.3 on 2021-03-19 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_agelimit_for_adults'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='empty',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
