# Generated by Django 3.1.3 on 2021-03-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0010_auto_20210319_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
