# Generated by Django 3.1.7 on 2021-04-13 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advuser',
            name='phone',
            field=models.CharField(blank=True, default='89898957854', max_length=11, null=True, unique=True),
        ),
    ]
