# Generated by Django 3.1.7 on 2021-04-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20210413_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='username',
        ),
    ]
