# Generated by Django 3.1.7 on 2021-04-13 14:30

from django.db import migrations
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20210413_1924'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='advuser',
            managers=[
                ('objects', user.models.UserAccountManager()),
            ],
        ),
    ]
