# Generated by Django 3.1.7 on 2021-04-17 12:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20210413_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='advuser',
            name='bonuses',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
