# Generated by Django 3.1.7 on 2021-04-17 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20210417_1738'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advuser',
            name='phone',
        ),
    ]
