# Generated by Django 3.1.3 on 2021-01-07 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_braintree_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
