# Generated by Django 3.1.3 on 2021-02-07 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_delete_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/%Y/%M/%M'),
        ),
        migrations.AddField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
