# Generated by Django 3.1.3 on 2021-02-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0009_auto_20210207_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='url',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/', max_length=200),
        ),
    ]
