# Generated by Django 3.1.7 on 2021-04-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0012_order_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone',
        ),
    ]
